#!/usr/bin/env python
from misc.utility.scons_hints import *

Import("env")

# Add current directory to include path so that files in subfolders
# can include each other using paths relative to the module root.
env.Append(CPPPATH=["."])

env.add_source_files(env.modules_sources, "*.cpp")
env.add_source_files(env.modules_sources, "core/*.cpp")
env.add_source_files(env.modules_sources, "resources/*.cpp")
env.add_source_files(env.modules_sources, "scene/*.cpp")
